global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "metamapa-services"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "metamapa-service:9000"
          - "fuente-dinamica:9001"
          - "fuente-estatica:9002"
          - "estadistica-service:9008"
          - "agregador:9004"
          - "usuarios-service:9005"
          - "fuente-demo:9006"
          - "fuente-metamapa:9007"